module.exports = {
	// 公共错误码(只留部分)
	'ActionOffline': '接口已下线。',
	'AuthFailure.InvalidSecretId': '密钥非法（不是云 API 密钥类型）。',
	'AuthFailure.SecretIdNotFound': '密钥错误或不存在。请检查密钥(SecretId)是否填写正确，注意前后不得有空格。',
	'AuthFailure.SignatureExpire': '签名过期。Timestamp 和服务器时间相差不得超过五分钟，请检查本地时间是否和标准时间同步。',
	'AuthFailure.SignatureFailure': '签名错误。请确认签名生成方法(SecretKey)是否正确。',
	'AuthFailure.UnauthorizedOperation': '请求未授权。请参考 CAM 文档对鉴权的说明。',
	'IpInBlacklist': 'IP地址在黑名单中。',
	'IpNotInWhitelist': 'IP地址不在白名单中。',
	'LimitExceeded': '超过配额限制。',
	'RequestLimitExceeded': '请求的次数超过了频率限制。',
	// 业务错误码
	'FailedOperation.ErrorUserArea': '用户区域与请求服务区域不一致。',
	'FailedOperation.LanguageRecognitionErr': '暂时无法识别该语种。',
	'FailedOperation.NoFreeAmount': '本月免费额度已用完，如需继续使用您可以在机器翻译控制台升级为付费使用。',
	'FailedOperation.RequestAiLabErr': '内部请求错误。',
	'FailedOperation.ServiceIsolate': '账号因为欠费停止服务，请在腾讯云账户充值。',
	'FailedOperation.StopUsing': '账号已停服。',
	'FailedOperation.UserNotRegistered': '服务未开通，请在腾讯云官网机器翻译控制台开通服务。',
	'InternalError.BackendTimeout': '后台服务超时，请稍后重试。',
	'InternalError.ErrorGetRoute': '路由获取错误。',
	'InternalError.ErrorUnknown': '未知错误。',
	'InternalError.RequestFailed': '请求失败。',
	'InvalidParameter.MissingParameter': '参数错误。',
	'LimitExceeded.LimitedAccessFrequency': '超出请求频率。',
	'RequestLimitExceeded.UinLimitExceeded': '超出UIN使用限额。',
	'UnauthorizedOperation.ActionNotFound': '请填写正确的Action字段名称。',
	'UnsupportedOperation.TextTooLong': '单次请求text超过长度限制。',
	'UnsupportedOperation.UnSupportedTargetLanguage': '不支持的目标语言，请参照语言列表。',
	'UnsupportedOperation.UnsupportedLanguage': '不支持的语言，请参照语言列表。',
	'UnsupportedOperation.UnsupportedSourceLanguage': '不支持的源语言，请参照语言列表。',
};